version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - hotels

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "28090:80"
    networks:
      - hotels
    depends_on:
      - php-fpm

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
      POSTGRES_DB: hotels
    ports:
      - "26432:5432"
    networks:
      - hotels

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-25060}:80"
    networks:
      - hotels
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "26379:6379"
    networks:
      - hotels

networks:
  hotels:
    driver: bridge
